title = "Aloha's Blog"
baseURL = 'https://daisilia.com'
theme = 'daisilia'
enableEmoji = true
hasCJKLanguage = true
paginate = 10
paginatePath = 'page'

# language
languageCode = 'zh-cn'
defaultContentLanguage = 'zh'
[languages.zh]
  languagedirection = 'zh'
  title = "Aloha's Blog"
  weight = 10

# enableGitInfo = false
[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = ['lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']

[author]
  fullname = "Qihuan Liu"
  nickname = "Aloha"
  avatar = "/images/avatar.jpg"
  homepage = "https://daisilia.com"

[taxonomies]
  tag = 'tags'
  # category = 'categories'

# menus
[menu]
[[menu.daisy]]
  identifier = 'home'
  name = 'Home'
  pre = '<i class="fas fa-home"></i>'
  url = '/'
  weight = 1
[[menu.daisy]]
  identifier = 'about'
  name = 'About'
  pre = '<i class="fas fa-user"></i>'
  url = '/about/'
  weight = 2
[[menu.daisy]]
  identifier = 'tags'
  name = 'Tags'
  pre = '<i class="fas fa-tags"></i>'
  url = '/tags/'
  weight = 3
# [[menu.daisy]]
#   identifier = 'categories'
#   name = 'Categories'
#   pre = '<i class="fas fa-th-list"></i>'
#   url = '/categories/'
#   weight = 4
[[menu.daisy]]
  identifier = 'cards'
  name = 'Cards'
  pre = '<i style="line-height:15px;vertical-align:middle;"><svg version="1.1" id="svg10094" xml:space="preserve" width="16.534685" height="15.297463" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg"><defs id="defs10098" /><sodipodi:namedview id="namedview10096" pagecolor="#ffffff" bordercolor="#999999" borderopacity="1" inkscape:showpageshadow="0" inkscape:pageopacity="0" inkscape:pagecheckerboard="0" inkscape:deskcolor="#d1d1d1" /><inkscape:clipboard min="315.37789,349.81892" max="331.91257,365.11639" geom-min="315.37789,349.81892" geom-max="331.91257,365.11638" /><g id="g10100" transform="matrix(3.7795276,0,0,3.7795276,-315.37789,-349.81893)"><rect style="fill:#777777;stroke:#333333;stroke-width:0;stroke-linejoin:round;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;paint-order:stroke fill markers;stop-color:#000000" id="rect7046-2" width="2.6458323" height="3.174999" x="-87.818535" y="93.428711" ry="0.40289268" rx="0.3713097" transform="scale(-1,1)" /><rect style="fill:#555555;stroke:#333333;stroke-width:0;stroke-linejoin:round;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;paint-order:stroke fill markers;stop-color:#000000" id="rect7046-2-0" width="2.6458323" height="3.174999" x="-39.971855" y="119.56335" ry="0.40289268" rx="0.3713097" transform="matrix(-0.91098326,0.41244333,0.41244333,0.91098326,0,0)" /></g></svg></i>'
  url = '/cards/'
  weight = 4
[[menu.daisy]]
  identifier = 'series'
  name = 'Series'
  pre = '<i class="fas fa-book"></i>'
  url = '/series/'
  weight = 5
# [[menu.daisy]]
#   pre = '<i class="fas fa-search"></i>'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[caches]
  [caches.getresource]
    dir = ':resourceDir/_gen'
    # maxAge = "72h"
    maxAge = -1

[module]
[[module.mounts]]
  source = 'content'
  target = 'content'
  # exclude Rmarkdown files
  excludeFiles = ['**.Rmd', '**.Rmarkdown', '**.drawio']
