defaultMarkdownHandler = 'goldmark'
[goldmark]
  [goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = 'github'
    [goldmark.parser.attribute]
      block = true
      title = true
  [goldmark.renderer]
    hardWraps = true
    unsafe = true
    xhtml = true
[highlight]
  anchorLineNos = false
  lineAnchors = ''
  codeFences = true
  guessSyntax = true
  lineNos = true
  lineNumbersInTable = false
  noClasses = true
  style = 'monokailight' # see https://xyproto.github.io/splash/docs/all.html
  tabWidth = 4
  hl_Lines = ''
  lineNoStart = 1
[tableOfContents]
  ordered = false
  startLevel = 2
  endLevel = 6
